### ISSUE TITLE
 useState variable is set directly without using setter function

### ISSUE THREAD

**Issue by Sumithra-Suresh** [fac25/week5-Abby-Joe#17]
In useEffect(), line #63, state variable is set directly.

```
if (card.src === firstChoice) {
            card.matched = true
          }
```

```
  const [cards, setCards] = useState([]);
```
Instead, we need to use setCards to set the card.matched value.

**Comment by Abbbyccc** [comment]
Thank you @Sumithra-Suresh  matched is actually a key in the card array thank you!
