### ISSUE TITLE
🎉  Compliments 🥳 

### ISSUE THREAD

**Issue by PJSalter** [fac25/week5-Abby-Joe#19]
A really good effort on this project 🤩 Well Done 🌈  

Code is easy to follow when reading it 🌟  Very neat.

https://github.com/fac25/week5-Abby-Joe/blob/4cde6c7f023f5f38a41c91164d10017a606f3d27/src/Pages/Game.jsx#L21

**Comment by Abbbyccc** [comment]
Thank you @PJSalter
