### ISSUE TITLE
Use user's name

### ISSUE THREAD

**Issue by ivan-unfolds** [fac25/week5-Abby-Joe#21]
There is an input field in `Home.js` for the user's name but you're not using it to display their name in `Game.js`.

https://github.com/fac25/week5-Abby-Joe/blob/bc6b6bbf31600b2d7478e9ba9a2b678d39a6e8bc/src/Pages/Home.jsx#L7

One way you could do this is using `useSearchParams` hook from react router.

**Comment by Joe-Lindie** [comment]
Thank you for your help, Ivan!  💯
